title: Albert's Homepage
email: al5932@nyu.edu
description: >-
    This is my homepage!
baseurl: "" # site subpath, e.g. /blog
url: "http://a1liu.github.io"
markdown: kramdown
strict_front_matter: true

exclude: [scripts,env]
collections_dir: collections
includes_dir: src/_includes
layouts_dir: src/_layouts
sass: # http://markdotto.com/2014/09/25/sass-and-jekyll/
  sass_dir: src/_sass

repo-url: "https://github.com/A1Liu/a1liu.github.io"
yikes: This hasn't been made yet! Yikes.
special_chars:
    newline: "\n"
    tab: "\t"

collections:
    main:
        output: true
        permalink: /:name
    posts:
        output: true
        permalink: /blog/:year/:month/:title/
    resources:
        output: true
        permalink: /resources/:name

defaults:
    -
        scope:
            type: "pages"
            path: "" # an empty string here means all files in the project
        values:
            layout: "page"
    -
        scope:
            type: "posts"
            path: ""
        values:
            layout: "post"
    -
        scope:
            type: "main"
            path: ""
        values:
            layout: "page"
