title: Albert's Homepage
email: al5932@nyu.edu
description: >-
    This is my homepage!
baseurl: "" # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site, e.g. http://example.com
url: "http://a1liu.github.io"
markdown: kramdown
collections_dir: collections
exclude: [scripts,env]
yikes: This hasn't been made yet! Yikes.

special_chars:
    newline: "\n"
    tab: "\t"
# End custom settings

collections:
    main:
        output: true
        permalink: /:name
    posts:
        output: true
        permalink: /blog/:year/:month/:title/
    resources:
        output: true
        permalink: /resources/:name

defaults:
    -
        scope:
            type: "pages"
            path: "" # an empty string here means all files in the project
        values:
            layout: "page"
    -
        scope:
            type: "posts"
            path: ""
        values:
            layout: "post"
    -
        scope:
            type: "main"
            path: ""
        values:
            layout: "page"
