title: Albert Liu
email: al5932@nyu.edu
description: >-
    This is my homepage!
url: "http://a1liu.github.io"
strict_front_matter: true
markdown: kramdown
theme: jekyll-theme-docgen
remote_theme: A1Liu/docgen

# feat: Add YAML String Concatenation to Jekyll
exclude: [scripts, env, build.py, LICENSE, README.md]
include: [_collections]
assets_dir: "/assets"
collections_dir: src/_collections
includes_dir: src/_includes
layouts_dir: src/_layouts
sass: # http://markdotto.com/2014/09/25/sass-and-jekyll/
  sass_dir: src/_sass

repo-url: "https://github.com/A1Liu/a1liu.github.io"
special_chars:
  newline: "\n"
  tab: "\t"

collections:
  main:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
  resources:
    output: true
    permalink: /resources/:name
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  -
    scope:
      type: pages
    values: &default_values
      layout: page
      head-include: global/head.html
      header-include: global/header.html
      footer-include: global/footer.html
      scripts-include: global/scripts.html
  -
    scope:
      type: posts
    values: *default_values

  -
    scope:
      type: main
    values: *default_values
  -
    scope:
      type: docs
    values:
      layout: latex
      head-include: docs/head.html
      footer-include: docs/footer.html
      scripts-include: global/scripts.html
