title: Albert Liu
email: al5932@nyu.edu
description: >-
    This is my homepage!
url: "http://a1liu.github.io"
strict_front_matter: true
markdown: kramdown
wearables_url: "/wearables-blog"
theme: jekyll-theme-docgen
remote_theme: A1Liu/docgen

exclude: [scripts, env, build.py, LICENSE, README.md, Gemfile]

github_path: "A1liu/a1liu.github.io"
special_chars:
  newline: "\n"
  tab: "\t"

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/
  resources:
    output: true
    permalink: /resources/:name
  docs:
    output: true
    permalink: /docs/:path/
  career:
    output: true
    permalink: /career/:name/

defaults:
  -
    scope:
      type: pages
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      layout: page
  -
    scope:
      type: career
    values:
      layout: latex_no_title
  -
    scope:
      type: docs
    values:
      layout: latex
